config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  resources :welcomes, only: :index
  resources :tops, only: :index
  resources :codes, only: :index
  resources :editors, only: :index
  resources :results, only: :show
  resources :lessons, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :technicals, only: :index
  resources :code_golf_rankings, only: [:index, :show]
  resources :clouds, only: [:index]
  get 'clouds/compiler/:user_id', to: 'clouds#compiler', as: 'clouds_compiler'
  post 'clouds/token', to: 'clouds#generate_token'

  # 管理者ページ用
  resources :questions, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :categories, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :admins, only: :index
  get 'admins/answer/:id/:user_id', to: 'admins#answer', as: 'answer'
  get 'admins/list/:id/', to: 'admins#list', as: 'list'
  get 'admins/user/:id', to: 'admins#user', as: 'user'

  # ログイン認証
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: "sessions#destroy", as: :signout

  namespace :api do
    post '/admin/tweet', to: 'admin#tweet'
    get '/language/information/:language/:data', to: 'language#information'
  end

  # ユーザ用API
  namespace :api do
    namespace :v1 do
      get '/user/period', to: 'user#period'
      get '/heatmap/index', to: 'heatmap#index'
      get '/heatmap/data/:year', to: 'heatmap#data'
      get '/heatmap/show/:id', to: 'heatmap#show'
      post '/compile/exec', to: 'compile#exec'
      post '/judgement/exec', to: 'judgement#exec'
      get '/information/state', to: 'information#state'
      get '/information/result', to: 'information#result'
      get '/information/code', to: 'information#code'
      get '/information/all_code', to: 'information#all_code'
    end
    namespace :v2 do
      get '/cloud/language_map', to: 'cloud#get_language_map'
      post 'cloud/compiler', to: 'cloud#compiler'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/code_golf_rankings_controller.rb
class CodeGolfRankingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @results = @question.results

    # ランキングを格納するハッシュ
    @ranking_hash = {}

    # ランキングを格納(尚、使われていない言語のランキングは出てこない)
    @results.each do |result|
      next unless result.answer
      @ranking_hash[:"#{result.language}"] = result unless @ranking_hash.has_key?(:"#{result.language}")
      @ranking_hash[:"#{result.language}"] = result if @ranking_hash[:"#{result.language}"].code.length > result.code.length
    end
  end
end

app/views/code_golf_rankings/index.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'TOP', tops_path %>
  </li>
  <li>
    <%= link_to 'Editor', editors_path %>
  </li>
  <li>
    <%= link_to 'Category', sections_path %>
  </li>
  <li>
    <%= link_to 'Questions list', lessons_path %>
  </li>
  <li class="active">
    <%= link_to 'Technical', technicals_path %>
  </li>
</ul>
<h1 style="text-align: center">Code Golf Ranking</h1>
<p style="text-align: center">誰よりもコードを短く記述することを極めたい人に</p>
<ul>
  <% @questions.each do |question| %>
    <h3><li><%= link_to question.title, code_golf_ranking_path(question.id) %></li></h3>
  <% end %>
</ul>

app/views/code_golf_rankings/show.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'TOP', tops_path %>
  </li>
  <li>
    <%= link_to 'Editor', editors_path %>
  </li>
  <li>
    <%= link_to 'Category', sections_path %>
  </li>
  <li>
    <%= link_to 'Questions list', lessons_path %>
  </li>
  <li class="active">
    <%= link_to 'Technical', technicals_path %>
  </li>
</ul>

<h1 style="text-align: center">Code Golf Ranking</h1>
<p style="text-align: center">誰よりもコードを短く記述することを極めたい人に</p>
<h3 style="text-align: center">問題名: <%= link_to @question.title, lesson_path(@question) %></h3>

<% @ranking_hash.each do |key, value| %>
  <div class="panel panel-info">
    <div class="panel-heading">
      言語: <%= key %>
    </div>
    <div class="panel-body">
      <label>文字数</label>
      <%= value.code.length %>
      <% if current_user.id == value.user_id %>
        <p style="color: green">このランキングのトップはあなたです。</p>
          <p>
            <%= sanitize markdown(value.code).html_safe %>
          </p>
      <% else %>
        <p>このランキングのトップはあなたではありません。</p>
      <% end %>
    </div>
  </div>
<% end %>