config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  resources :welcomes, only: :index
  resources :tops, only: :index
  resources :codes, only: :index
  resources :editors, only: :index
  resources :results, only: :show
  resources :lessons, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :technicals, only: :index
  resources :code_golf_rankings, only: [:index, :show]
  resources :clouds, only: [:index]
  get 'clouds/compiler/:user_id', to: 'clouds#compiler', as: 'clouds_compiler'
  post 'clouds/token', to: 'clouds#generate_token'

  # 管理者ページ用
  resources :questions, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :categories, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :admins, only: :index
  get 'admins/answer/:id/:user_id', to: 'admins#answer', as: 'answer'
  get 'admins/list/:id/', to: 'admins#list', as: 'list'
  get 'admins/user/:id', to: 'admins#user', as: 'user'

  # ログイン認証
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: "sessions#destroy", as: :signout

  namespace :api do
    post '/admin/tweet', to: 'admin#tweet'
    get '/language/information/:language/:data', to: 'language#information'
  end

  # ユーザ用API
  namespace :api do
    namespace :v1 do
      get '/user/period', to: 'user#period'
      get '/heatmap/index', to: 'heatmap#index'
      get '/heatmap/data/:year', to: 'heatmap#data'
      get '/heatmap/show/:id', to: 'heatmap#show'
      post '/compile/exec', to: 'compile#exec'
      post '/judgement/exec', to: 'judgement#exec'
      get '/information/state', to: 'information#state'
      get '/information/result', to: 'information#result'
      get '/information/code', to: 'information#code'
      get '/information/all_code', to: 'information#all_code'
    end
    namespace :v2 do
      get '/cloud/language_map', to: 'cloud#get_language_map'
      post 'cloud/compiler', to: 'cloud#compiler'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v2/cloud_controller.rb
require './lib/code_candy/code_runner'
require './lib/code_candy/language'

class Api::V2::CloudController < Api::ApiController
  before_action :authenticate_api_token
  protect_from_forgery except: :compiler

  # C3 APIで利用できるプログラミング言語の一覧を取得する
  def get_language_map
    languages = CodeCandy::Language.get_language_data
    language_map = {}

    languages.each do |key, value|
      puts key
      language_map[key] = value[:language]
    end

    render json: language_map
  end

  # APIとして利用できるコンパイラ
  def compiler
    # 送られてきたパラメータを変数に格納
    language = params[:language]
    source_code = params[:source_code]
    input = params[:input]

    code_runner = CodeCandy::CodeRunner.new(language, source_code, input, auth_user.id)

    begin
      submit_language = CodeCandy::Language.get_language_data[:"#{language}"][:language]
      # 提出されたコードを保存
      @result = code_runner.exec
      # 入力が不正な場合はレコードしない
      CloudCompiler.create(code: source_code, language: submit_language, user_id: auth_user.id) unless @result[:input_error]
    rescue
      @result = {stdout: "Error",stderr: "入力が不正です。", time: "", exit_code: 1, input_error: true}
    end

    @result[:stdout] = @result[:stdout].force_encoding("UTF-8")
    @result[:stderr] = @result[:stderr].force_encoding("UTF-8")

    render json: @result
  end
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def generate_token
    current_user.regenerate_api_token
    flash[:create_token] = "Successful create token!!"
    redirect_to clouds_path
  end

  def compiler
    @cloud_compilers = CloudCompiler.where(user_id: params[:user_id])
  end

  private
  def set_user
    @user = User.find(params[:user_id])
  end
end

app/views/clouds/compiler.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'TOP', tops_path %>
  </li>
  <li>
    <%= link_to 'Editor', editors_path %>
  </li>
  <li>
    <%= link_to 'Category', sections_path %>
  </li>
  <li>
    <%= link_to 'Questions list', lessons_path %>
  </li>
  <li class="active">
    <%= link_to 'Technical', technicals_path %>
  </li>
</ul>
<h1 style="text-align: center;">Cloud Compiler API</h1>
<%= link_to '< Back', clouds_path, class: 'btn btn-info' %>
<div class="panel panel-default">
  <div class="panel panel-heading">
    <h3 style="text-align: center">API 利用ログ</h3>
  </div>
  <div class="panel panel-body">
    <h3>利用数: <%= @cloud_compilers.count %></h3>
    <hr />
    <% @cloud_compilers.each do |cloud_compiler| %>
      <p>
        <%= sanitize markdown(cloud_compiler.code).html_safe %>
      </p>
      <p>
        <label>言語</label>
        <%= cloud_compiler.language %>
      </p>
      <p>
        <label>入力</label>
        <%= cloud_compiler.input %>
      </p>
      <p>
        <label>実行日時</label>
        <%= cloud_compiler.created_at.in_time_zone('Tokyo').strftime("%Y年 %m月 %d日 %H:%M:%S") %>
      </p>
      <hr />
    <% end %>
  </div>
</div>

app/views/clouds/index.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'TOP', tops_path %>
  </li>
  <li>
    <%= link_to 'Editor', editors_path %>
  </li>
  <li>
    <%= link_to 'Category', sections_path %>
  </li>
  <li>
    <%= link_to 'Questions list', lessons_path %>
  </li>
  <li class="active">
    <%= link_to 'Technical', technicals_path %>
  </li>
</ul>
<h1 style="text-align: center;">Cloud API</h1>
<p style="text-align: center;">CodeCandyのAPIを使ってプログラミングをさらに楽しむ</p>
<div style="font-size: 200%">
  <lable>API Token</label>
  <code>
    <%= current_user.api_token %>
  </code>
</div>
<p style="color: green;"><%= h(flash[:create_token]) %></p>
<%= form_with url: clouds_token_path, local: true do |f|%>
  <%= f.submit "新しいAPI Tokenを生成", class: "btn btn-primary" %>
<% end %>
<hr />
<h2>CodeCandy Cloud API(C3 API)とは</h2>
<p>
  CodeCandy Cloud API(C3 API)とは、CodeCandyの機能をより最大限に利用してもらえるよう開発されたWeb APIです。<br />
  クラウドサービスを使ったサービス開発の入門や、システム開発にお使いください。
</p>
<h2>APIの使い方</h2>
<p>
  C3 APIはWeb APIとして提供されているので、APIに対してHTTPリクエストを送信することで利用していただけます。<br />
  C3 APIのAPIは上記のユーザのAPI Tokenを使ってユーザ認証を行っています。<br />
  Request headerに<code>Authorization: Token ${ユーザのAPI Token}</code>を追加してください。
</p>
<h2>C3 API End point</h2>
<p>
  現在、利用できるAPIです。随時追加予定です。
</p>
<table class="table">
  <thead>
    <tr>
      <th>API Name</th>
      <th>End point</th>
      <th>Method</th>
      <th>概要</th>
      <th>Request Body(Example)</th>
      <th>Response</th>
      <th>利用詳細</th>
      <th>注意事項</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>LangMap</td>
      <td><code>/api/v2/cloud/language_map</code></td>
      <td>GET</td>
      <td>
        C3 APIで利用できるプログラミング言語一覧を取得することができます。<br />
        keyが実行できるプログラミング言語、valueがCodeCandyに保存される値、のjsonを返却します。
      </td>
      <td>
      </td>
      <td>
        <code>
          {
            ${String}: ${String},
            ...
            ${String}: ${String}
          }
        </code>
      </td>
      <th></th>
    </tr>
    <tr>
      <td>Cloud Compiler API(CCA)</td>
      <td><code>/api/v2/cloud/compiler</code></td>
      <td>POST</td>
      <td>
        指定した言語のプログラムを実行することができます。
      </td>
      <td>
        <code>
          {
            "language": "ruby",
            "source_code": "puts 123",
            "input": ""
          }
        </code>
      </td>
      <td>
        <code>
          {
            "stdout": ${String},
            "stderr": ${String},
            "time": ${String},
            "exit_code": ${Integer},
            "input_error": ${Boolean}
          }
        </code>
      </td>
      <td>
        <%= link_to '利用詳細', clouds_compiler_path(current_user.id), class: 'btn btn-primary' %>
      </td>
      <td>
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#cloud_compiler_notes">open</button>
      </td>
    </tr>
    <div class="modal fade" id="cloud_compiler_notes">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Cloud Compiler APIを利用するにあたっての注意事項</h4>
          </div>
          <div class="modal-body">
            <p>
              Cloud Compiler APIは利用履歴をすべて保存しています。ソースコードや標準入力に外部に公開してはいけない情報を書かないでください。<br />
              また、Cloud Compiler APIを利用して発生した問題に関して、管理者は一切の責任を負いません。予めご了承ください。
            </p>
          </div>
        </div>
      </div>
    </div>
  </tbody>
</table>