config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  resources :welcomes, only: :index
  resources :tops, only: :index
  resources :codes, only: :index
  resources :editors, only: :index
  resources :results, only: :show
  resources :lessons, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :technicals, only: :index
  resources :code_golf_rankings, only: [:index, :show]
  resources :clouds, only: [:index]
  get 'clouds/compiler/:user_id', to: 'clouds#compiler', as: 'clouds_compiler'
  post 'clouds/token', to: 'clouds#generate_token'

  # 管理者ページ用
  resources :questions, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :categories, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :admins, only: :index
  get 'admins/answer/:id/:user_id', to: 'admins#answer', as: 'answer'
  get 'admins/list/:id/', to: 'admins#list', as: 'list'
  get 'admins/user/:id', to: 'admins#user', as: 'user'

  # ログイン認証
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: "sessions#destroy", as: :signout

  namespace :api do
    post '/admin/tweet', to: 'admin#tweet'
    get '/language/information/:language/:data', to: 'language#information'
  end

  # ユーザ用API
  namespace :api do
    namespace :v1 do
      get '/user/period', to: 'user#period'
      get '/heatmap/index', to: 'heatmap#index'
      get '/heatmap/data/:year', to: 'heatmap#data'
      get '/heatmap/show/:id', to: 'heatmap#show'
      post '/compile/exec', to: 'compile#exec'
      post '/judgement/exec', to: 'judgement#exec'
      get '/information/state', to: 'information#state'
      get '/information/result', to: 'information#result'
      get '/information/code', to: 'information#code'
      get '/information/all_code', to: 'information#all_code'
    end
    namespace :v2 do
      get '/cloud/language_map', to: 'cloud#get_language_map'
      post 'cloud/compiler', to: 'cloud#compiler'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/technicals_controller.rb
class TechnicalsController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/views/technicals/index.html.erb
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'TOP', tops_path %>
  </li>
  <li>
    <%= link_to 'Editor', editors_path %>
  </li>
  <li>
    <%= link_to 'Category', sections_path %>
  </li>
  <li>
    <%= link_to 'Questions list', lessons_path %>
  </li>
  <li class="active">
    <%= link_to 'Technical', technicals_path %>
  </li>
</ul>
<h1 style="text-align: center">テクニカル</h1>
<h5 style="text-align: center">プログラミングをもっと楽しもう</h5>
<!--
<div class="panel panel-info">
  <div class="panel panel-heading">
    テクニカルとは
  </div>
  <div class="panel panel-body">
  </div>
</div>
-->
<ul>
  <h3><li><%= link_to "Code golf ranking", code_golf_rankings_path %></li></h3>
  <h3><li><%= link_to "Cloud API", clouds_path %></li></h3>
</ul>