config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  resources :welcomes, only: :index
  resources :tops, only: :index
  resources :codes, only: :index
  resources :editors, only: :index
  resources :results, only: :show
  resources :lessons, only: [:index, :show]
  resources :sections, only: [:index, :show]
  resources :technicals, only: :index
  resources :code_golf_rankings, only: [:index, :show]
  resources :clouds, only: [:index]
  get 'clouds/compiler/:user_id', to: 'clouds#compiler', as: 'clouds_compiler'
  post 'clouds/token', to: 'clouds#generate_token'

  # 管理者ページ用
  resources :questions, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :categories, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :admins, only: :index
  get 'admins/answer/:id/:user_id', to: 'admins#answer', as: 'answer'
  get 'admins/list/:id/', to: 'admins#list', as: 'list'
  get 'admins/user/:id', to: 'admins#user', as: 'user'

  # ログイン認証
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: "sessions#destroy", as: :signout

  namespace :api do
    post '/admin/tweet', to: 'admin#tweet'
    get '/language/information/:language/:data', to: 'language#information'
  end

  # ユーザ用API
  namespace :api do
    namespace :v1 do
      get '/user/period', to: 'user#period'
      get '/heatmap/index', to: 'heatmap#index'
      get '/heatmap/data/:year', to: 'heatmap#data'
      get '/heatmap/show/:id', to: 'heatmap#show'
      post '/compile/exec', to: 'compile#exec'
      post '/judgement/exec', to: 'judgement#exec'
      get '/information/state', to: 'information#state'
      get '/information/result', to: 'information#result'
      get '/information/code', to: 'information#code'
      get '/information/all_code', to: 'information#all_code'
    end
    namespace :v2 do
      get '/cloud/language_map', to: 'cloud#get_language_map'
      post 'cloud/compiler', to: 'cloud#compiler'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  comment    :text
#

class Category < ApplicationRecord
  validates :title, {presence: true, uniqueness: true}

  has_many :category_items
  has_many :questions, through: :category_items, dependent: :destroy

  accepts_nested_attributes_for :questions
  # has_many :category_items

  include FriendlyId
  friendly_id :title
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :all_questions, only: [:new, :edit]

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admins_path
  end

  private
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def all_questions
    @questions = Question.all
  end

  def category_params
    params.require(:category).permit(:title, :comment, { question_ids: [] })
  end
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |f| %>
  <div class="field">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :title, "コメント" %>
    <%= f.text_field :comment, class: "form-control" %>
  </div>

  <label style="margin-top: 1em">問題一覧</label>
  <%= f.collection_check_boxes(:question_ids, Question.all, :id, :title, include_hidden: false, prompt: true) do |b|%>
    <ul style="list-style-type: none">
      <li><%= b.label { b.check_box + b.text } %></li>
    </ul>
  <% end %>

  <div class="action" style="margin-top: 1em">
    <%= f.submit "登録", class: "btn btn-primary", style: "margin-bottom: 1em" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>カテゴリー編集</h1>
<%= render 'form' %>

app/views/categories/new.html.erb
<h1>カテゴリー追加</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 style="margin-bottom: 1em">カテゴリー: <%= @category.title %></h1>
<p style="margin-bottom: 1em"><%= @category.comment %></p>
<table class="table">
  <thead>
    <tr>
      <td>問題名</td>
    </tr>
  </thead>
  <tbody>
    <% @category.category_items.order(created_at: 'asc').each do |item| %>
      <tr>
        <td><%= link_to Question.find(item.question_id).title, question_path(item.question_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="actions">
  <%= link_to "管理画面", admins_path, class: "btn btn-info" %>
  <%= link_to "カテゴリーページ",
    section_path(@category),
    class: "btn btn-info" %>
  <%= link_to "カテゴリー追加", new_category_path, class: "btn btn-primary" %>
  <%= link_to "編集", edit_category_path(@category), class: "btn btn-primary" %>
  <%= link_to "削除",
    category_path(@category),
    method: :delete,
    class: "btn btn-danger",
    data: {confirm: "本当に削除していいですか？"} %>
</div>